services:
  website:
    build: .
    hostname: ponycon-website
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - ./data/config.json:/app/data/config.json
      - ./data/events.xml:/app/data/events.xml
      - ./assets/events:/app/assets/events
  admin:
    build: ./admin
    hostname: ponycon-admin
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - ./admin:/var/www/html
      - ./data:/data
      - ./assets:/assets

networks:
  proxy:
    name: "proxy"
    external: true