services:
  website:
    build: .
    hostname: ponycon-website
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - ./data/config.json:/app/data/config.json
      - ./data/events.xml:/app/data/events.xml
      - ./assets/events:/app/assets/events

networks:
  proxy:
    name: "proxy"
    external: true